name: shartflix
description: "Shartflix app."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2


  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  lottie: ^2.7.0
  dio: ^5.3.3
  image_picker: ^1.1.2
  cupertino_icons: ^1.0.8
  provider: ^6.0.5
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.13.1

# ðŸ”´
flutter_native_splash:
  color: "#000000"
  android: true
  ios: true
  android_12:
    color: "#000000"

# App Icon
flutter_icons:
  android: true
  ios: true
  image_path: assets/icons/app_icon.png
  min_sdk_android: 21

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/splash/
    - assets/lottie/pinkregistry.json
    - assets/lottie/shywolflgn.json
    - assets/mock/movies.json
    - assets/icons/google.png
    - assets/icons/apple.png
    - assets/icons/facebook.png


  fonts:
    - family: InstrumentSans
      fonts:
        - asset: assets/fonts/InstrumentSans/InstrumentSans[wdth,wght].ttf
        - asset: assets/fonts/InstrumentSans/InstrumentSans-Italic[wdth,wght].ttf
          style: italic
